export const AGREE_AND_CONTINUE = 'AGREE_AND_CONTINUE'

export const APP_STARTUP = 'APP_STARTUP'
export const APP_STARTUP_SUCCESS = 'APP_STARTUP_SUCCESS'

export const GO_TO_CONTACT = 'GO_TO_CONTACT'

export const ONBOARDING_INITIALIZE_SUCCESS = 'ONBOARDING_INITIALIZE_SUCCESS'

export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'

export const WEBSOCKET_CLOSE = 'WEBSOCKET_CLOSE'
export const WEBSOCKET_CONNECT = 'WEBSOCKET_CONNECT'
export const WEBSOCKET_OPEN = 'WEBSOCKET_OPEN'

///////////////////////////
// HOOLIGRAM V2 PROTOCOL //
///////////////////////////

export const AUTHORIZATION_SIGN_IN_FAILURE = 'AUTHORIZATION_SIGN_IN_FAILURE'
export const AUTHORIZATION_SIGN_IN_REQUEST = 'AUTHORIZATION_SIGN_IN_REQUEST'
export const AUTHORIZATION_SIGN_IN_SUCCESS = 'AUTHORIZATION_SIGN_IN_SUCCESS'

export const CONN_KEEP_ALIVE_FAILURE = 'CONN_KEEP_ALIVE_FAILURE'
export const CONN_KEEP_ALIVE_REQUEST = 'CONN_KEEP_ALIVE_REQUEST'
export const CONN_KEEP_ALIVE_SUCCESS = 'CONN_KEEP_ALIVE_SUCCESS'

export const VERIFICATION_REQUEST_CODE_FAILURE = 'VERIFICATION_REQUEST_CODE_FAILURE'
export const VERIFICATION_REQUEST_CODE_REQUEST = 'VERIFICATION_REQUEST_CODE_REQUEST'
export const VERIFICATION_REQUEST_CODE_SUCCESS = 'VERIFICATION_REQUEST_CODE_SUCCESS'

export const VERIFICATION_SUBMIT_CODE_FAILURE = 'VERIFICATION_SUBMIT_CODE_FAILURE'
export const VERIFICATION_SUBMIT_CODE_REQUEST = 'VERIFICATION_SUBMIT_CODE_REQUEST'
export const VERIFICATION_SUBMIT_CODE_SUCCESS = 'VERIFICATION_SUBMIT_CODE_SUCCESS'
