export const GO_TO_CONTACT = 'GO_TO_CONTACT'
export const GO_TO_CONTACT_CREATE = 'GO_TO_CONTACT_CREATE'
export const GO_TO_GROUP_CREATE = 'GO_TO_GROUP_CREATE'
export const GO_TO_GROUP_INFO = 'GO_TO_GROUP_INFO'
export const GO_TO_GROUP_LEAVE = 'GO_TO_GROUP_LEAVE'
export const GO_TO_GROUP_MEMBER_ADD = 'GO_TO_GROUP_MEMBER_ADD'
export const GO_TO_GROUP_MESSAGE = 'GO_TO_GROUP_MESSAGE'
export const GO_TO_HOME = 'GO_TO_HOME'
export const GO_TO_ONBOARDING_AGREE = 'GO_TO_ONBOARDING_AGREE'
export const GO_TO_ONBOARDING_INITIALIZE = 'GO_TO_ONBOARDING_INITIALIZE'
export const GO_TO_ONBOARDING_REQUEST = 'GO_TO_ONBOARDING_REQUEST'
export const GO_TO_ONBOARDING_SUBMIT = 'GO_TO_ONBOARDING_SUBMIT'
export const GO_TO_SPLASH = 'GO_TO_SPLASH'

export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'

export const WEBSOCKET_CLOSE = 'WEBSOCKET_CLOSE'
export const WEBSOCKET_CONNECT = 'WEBSOCKET_CONNECT'
export const WEBSOCKET_OPEN = 'WEBSOCKET_OPEN'

///////////////////////////
// HOOLIGRAM V2 PROTOCOL //
///////////////////////////

export const AUTHORIZATION_SIGN_IN_FAILURE = 'AUTHORIZATION_SIGN_IN_FAILURE'
export const AUTHORIZATION_SIGN_IN_REQUEST = 'AUTHORIZATION_SIGN_IN_REQUEST'
export const AUTHORIZATION_SIGN_IN_SUCCESS = 'AUTHORIZATION_SIGN_IN_SUCCESS'

export const CONN_KEEP_ALIVE_FAILURE = 'CONN_KEEP_ALIVE_FAILURE'
export const CONN_KEEP_ALIVE_REQUEST = 'CONN_KEEP_ALIVE_REQUEST'
export const CONN_KEEP_ALIVE_SUCCESS = 'CONN_KEEP_ALIVE_SUCCESS'

export const GROUP_CREATE_FAILURE = 'GROUP_CREATE_FAILURE'
export const GROUP_CREATE_REQUEST = 'GROUP_CREATE_REQUEST'
export const GROUP_CREATE_SUCCESS = 'GROUP_CREATE_SUCCESS'

export const GROUP_DELIVER_FAILURE = 'GROUP_DELIVER_FAILURE'
export const GROUP_DELIVER_REQUEST = 'GROUP_DELIVER_REQUEST'
export const GROUP_DELIVER_SUCCESS = 'GROUP_DELIVER_SUCCESS'

export const VERIFICATION_REQUEST_CODE_FAILURE = 'VERIFICATION_REQUEST_CODE_FAILURE'
export const VERIFICATION_REQUEST_CODE_REQUEST = 'VERIFICATION_REQUEST_CODE_REQUEST'
export const VERIFICATION_REQUEST_CODE_SUCCESS = 'VERIFICATION_REQUEST_CODE_SUCCESS'

export const VERIFICATION_SUBMIT_CODE_FAILURE = 'VERIFICATION_SUBMIT_CODE_FAILURE'
export const VERIFICATION_SUBMIT_CODE_REQUEST = 'VERIFICATION_SUBMIT_CODE_REQUEST'
export const VERIFICATION_SUBMIT_CODE_SUCCESS = 'VERIFICATION_SUBMIT_CODE_SUCCESS'
