export const APP_STARTUP = 'APP_STARTUP'
export const APP_STARTUP_SUCCESS = 'APP_STARTUP_SUCCESS'

export const PERSISTENCE_LOAD_STATE_FAILURE = 'PERSISTENCE_LOAD_STATE_FAILURE'
export const PERSISTENCE_LOAD_STATE_REQUEST = 'PERSISTENCE_LOAD_STATE_REQUEST'
export const PERSISTENCE_LOAD_STATE_SUCCESS = 'PERSISTENCE_LOAD_STATE_SUCCESS'

export const PERSISTENCE_SAVE_STATE_FAILURE = 'PERSISTENCE_SAVE_STATE_FAILURE'
export const PERSISTENCE_SAVE_STATE_REQUEST = 'PERSISTENCE_SAVE_STATE_REQUEST'
export const PERSISTENCE_SAVE_STATE_SUCCESS = 'PERSISTENCE_SAVE_STATE_SUCCESS'

export const SAVE_USER_NAME = 'SAVE_USER_NAME'

export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'

export const WEBSOCKET_CLOSE = 'WEBSOCKET_CLOSE'
export const WEBSOCKET_CONNECT = 'WEBSOCKET_CONNECT'
export const WEBSOCKET_OPEN = 'WEBSOCKET_OPEN'

// HOOLIGRAM PROTOCOL ACTIONS

export const AUTHORIZATION_SIGN_IN_REQUEST = 'AUTHORIZATION_SIGN_IN_REQUEST'
export const AUTHORIZATION_SIGN_IN_SUCCESS = 'AUTHORIZATION_SIGN_IN_SUCCESS'

export const MESSAGING_BROADCAST_REQUEST = 'MESSAGING_BROADCAST_REQUEST'
export const MESSAGING_BROADCAST_SUCCESS = 'MESSAGING_BROADCAST_SUCCESS'

export const VERIFICATION_REQUEST_CODE_FAILURE = 'VERIFICATION_REQUEST_CODE_FAILURE'
export const VERIFICATION_REQUEST_CODE_REQUEST = 'VERIFICATION_REQUEST_CODE_REQUEST'
export const VERIFICATION_REQUEST_CODE_SUCCESS = 'VERIFICATION_REQUEST_CODE_SUCCESS'

export const VERIFICATION_SUBMIT_CODE_FAILURE = 'VERIFICATION_SUBMIT_CODE_FAILURE'
export const VERIFICATION_SUBMIT_CODE_REQUEST = 'VERIFICATION_SUBMIT_CODE_REQUEST'
export const VERIFICATION_SUBMIT_CODE_SUCCESS = 'VERIFICATION_SUBMIT_CODE_SUCCESS'
