export const APP_STARTUP = 'APP:STARTUP'
export const APP_STARTUP_SUCCESS = 'APP:STARTUP_SUCCESS'

export const PERSISTENCE_LOAD_STATE_FAILURE = 'PERSISTENCE:LOAD_STATE_FAILURE'
export const PERSISTENCE_LOAD_STATE_REQUEST = 'PERSISTENCE:LOAD_STATE_REQUEST'
export const PERSISTENCE_LOAD_STATE_SUCCESS = 'PERSISTENCE:LOAD_STATE_SUCCESS'

export const PERSISTENCE_SAVE_STATE_FAILURE = 'PERSISTENCE:SAVE_STATE_FAILURE'
export const PERSISTENCE_SAVE_STATE_REQUEST = 'PERSISTENCE:SAVE_STATE_REQUEST'
export const PERSISTENCE_SAVE_STATE_SUCCESS = 'PERSISTENCE:SAVE_STATE_SUCCESS'

export const SAVE_USER_NAME = 'SAVE_USER_NAME'

export const VERIFICATION_REQUEST_CODE_FAILURE = 'API:VERIFICATION_REQUEST_CODE_FAILURE'
export const VERIFICATION_REQUEST_CODE_REQUEST = 'API:VERIFICATION_REQUEST_CODE_REQUEST'
export const VERIFICATION_REQUEST_CODE_SUCCESS = 'API:VERIFICATION_REQUEST_CODE_SUCCESS'

export const VERIFICATION_SUBMIT_CODE_FAILURE = 'API:VERIFICATION_SUBMIT_CODE_FAILURE'
export const VERIFICATION_SUBMIT_CODE_REQUEST = 'API:VERIFICATION_SUBMIT_CODE_REQUEST'
export const VERIFICATION_SUBMIT_CODE_SUCCESS = 'API:VERIFICATION_SUBMIT_CODE_SUCCESS'

export const API_AUTHORIZATION_SIGN_IN_REQUEST = 'API:AUTHORIZATION_SIGN_IN_REQUEST'
export const API_AUTHORIZATION_SIGN_IN_SUCCESS = 'API:AUTHORIZATION_SIGN_IN_SUCCESS'

export const MESSAGING_BROADCAST_REQUEST = 'API:MESSAGING_BROADCAST_REQUEST'
export const MESSAGING_BROADCAST_SUCCESS = 'API:MESSAGING_BROADCAST_SUCCESS'

export const WEBSOCKET_CLOSE = 'WEBSOCKET_CLOSE'
export const WEBSOCKET_OPEN = 'WEBSOCKET_OPEN'
