export const HOME = 'Home'
export const ONBOARDING_AGREE = 'OnboardingAgree'
export const ONBOARDING_INITIALIZE = 'OnboardingInitialize'
export const ONBOARDING_REQUEST_CODE = 'OnboardingRequestCode'
export const ONBOARDING_SUBMIT_CODE = 'OnboardingSubmitCode'
export const SPLASH = 'Splash'
