export default {
  GO_TO_CONTACT: 'GO_TO_CONTACT',
  GO_TO_CONTACT_CREATE: 'GO_TO_CONTACT_CREATE',
  GO_TO_DIRECT_MESSAGE: 'GO_TO_DIRECT_MESSAGE',
  GO_TO_GROUP_CREATE: 'GO_TO_GROUP_CREATE',
  GO_TO_GROUP_LEAVE: 'GO_TO_GROUP_LEAVE',
  GO_TO_GROUP_MEMBER_ADD: 'GO_TO_GROUP_MEMBER_ADD',
  GO_TO_GROUP_MESSAGE: 'GO_TO_GROUP_MESSAGE',
  GO_TO_HOME: 'GO_TO_HOME',
  GO_TO_ONBOARDING_AGREE: 'GO_TO_ONBOARDING_AGREE',
  GO_TO_ONBOARDING_INITIALIZE: 'GO_TO_ONBOARDING_INITIALIZE',
  GO_TO_ONBOARDING_REQUEST: 'GO_TO_ONBOARDING_REQUEST',
  GO_TO_ONBOARDING_SUBMIT: 'GO_TO_ONBOARDING_SUBMIT',
  GO_TO_SPLASH: 'GO_TO_SPLASH',

  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',

  WEBSOCKET_CLOSE: 'WEBSOCKET_CLOSE',
  WEBSOCKET_CONNECT: 'WEBSOCKET_CONNECT',
  WEBSOCKET_OPEN: 'WEBSOCKET_OPEN',

  ///////////////////////////
  // HOOLIGRAM V2 PROTOCOL //
  ///////////////////////////

  AUTHORIZATION_SIGN_IN_FAILURE: 'AUTHORIZATION_SIGN_IN_FAILURE',
  AUTHORIZATION_SIGN_IN_REQUEST: 'AUTHORIZATION_SIGN_IN_REQUEST',
  AUTHORIZATION_SIGN_IN_SUCCESS: 'AUTHORIZATION_SIGN_IN_SUCCESS',

  CONN_KEEP_ALIVE_FAILURE: 'CONN_KEEP_ALIVE_FAILURE',
  CONN_KEEP_ALIVE_REQUEST: 'CONN_KEEP_ALIVE_REQUEST',
  CONN_KEEP_ALIVE_SUCCESS: 'CONN_KEEP_ALIVE_SUCCESS',

  GROUP_CREATE_FAILURE: 'GROUP_CREATE_FAILURE',
  GROUP_CREATE_REQUEST: 'GROUP_CREATE_REQUEST',
  GROUP_CREATE_SUCCESS: 'GROUP_CREATE_SUCCESS',

  GROUP_ADD_MEMBER_FAILURE: 'GROUP_ADD_MEMBER_FAILURE',
  GROUP_ADD_MEMBER_REQUEST: 'GROUP_ADD_MEMBER_REQUEST',
  GROUP_ADD_MEMBER_SUCCESS: 'GROUP_ADD_MEMBER_SUCCESS',

  GROUP_DELIVER_FAILURE: 'GROUP_DELIVER_FAILURE',
  GROUP_DELIVER_REQUEST: 'GROUP_DELIVER_REQUEST',
  GROUP_DELIVER_SUCCESS: 'GROUP_DELIVER_SUCCESS',

  GROUP_LEAVE_FAILURE: 'GROUP_LEAVE_FAILURE',
  GROUP_LEAVE_REQUEST: 'GROUP_LEAVE_REQUEST',
  GROUP_LEAVE_SUCCESS: 'GROUP_LEAVE_SUCCESS',

  MESSAGING_DELIVER_FAILURE: 'MESSAGING_DELIVER_FAILURE',
  MESSAGING_DELIVER_REQUEST: 'MESSAGING_DELIVER_REQUEST',
  MESSAGING_DELIVER_SUCCESS: 'MESSAGING_DELIVER_SUCCESS',

  MESSAGING_SEND_FAILURE: 'MESSAGING_SEND_FAILURE',
  MESSAGING_SEND_REQUEST: 'MESSAGING_SEND_REQUEST',
  MESSAGING_SEND_SUCCESS: 'MESSAGING_SEND_SUCCESS',
  VERIFICATION_REQUEST_CODE_FAILURE: 'VERIFICATION_REQUEST_CODE_FAILURE',
  VERIFICATION_REQUEST_CODE_REQUEST: 'VERIFICATION_REQUEST_CODE_REQUEST',
  VERIFICATION_REQUEST_CODE_SUCCESS: 'VERIFICATION_REQUEST_CODE_SUCCESS',

  VERIFICATION_SUBMIT_CODE_FAILURE: 'VERIFICATION_SUBMIT_CODE_FAILURE',
  VERIFICATION_SUBMIT_CODE_REQUEST: 'VERIFICATION_SUBMIT_CODE_REQUEST',
  VERIFICATION_SUBMIT_CODE_SUCCESS: 'VERIFICATION_SUBMIT_CODE_SUCCESS'
}
